import { useState, useRef, useEffect, FormEvent } from "react";

export interface ChatMessage {
  role: "user" | "model";
  content: string;
}

type Props = {
  contractText: string;
  contractName: string;
};

export function ContractChat({ contractText, contractName }: Props) {
  const [messages, setMessages] = useState<ChatMessage[]>([]);
  const [input, setInput] = useState("");
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);

  const chatEndRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    chatEndRef.current?.scrollIntoView({ behavior: "smooth" });
  }, [messages, isLoading]);

  async function handleSubmit(e: FormEvent) {
    e.preventDefault();
    if (!input.trim() || isLoading) return;

    const userMessage = input.trim();
    setInput("");
    setError(null);
    setIsLoading(true);

    // Optimistically add user's message
    const updatedMessages = [...messages, { role: "user" as const, content: userMessage }];
    setMessages(updatedMessages);

    try {
      const response = await fetch("/api/chat", {
        method: "POST",
        headers: {
          "Content-Type": "application/json"
        },
        body: JSON.stringify({
          contractText,
          history: messages,
          newMessage: userMessage
        })
      });

      if (!response.ok) {
        const body = await response.json().catch(() => null);
        throw new Error(body?.error ?? `Server error: ${response.status}`);
      }

      const data = await response.json();
      setMessages([...updatedMessages, { role: "model", content: data.reply }]);
    } catch (err: unknown) {
      const msg = err instanceof Error ? err.message : "Failed to get response.";
      setError(msg);
    } finally {
      setIsLoading(false);
    }
  }

  return (
    <section id="chat" className="chat-section" aria-labelledby="chat-title">
      <div className="section-heading">
        <p className="eyebrow">Interactive analysis</p>
        <h2 id="chat-title">Ask questions about {contractName || "your contract"}.</h2>
        <p>
          Query any specific terms, clauses, or obligations in deep detail. 
          The assistant will only answer using details found in the contract.
        </p>
      </div>

      <div className="chat-container">
        <div className="chat-disclaimer" role="note">
          <strong>⚠️ Disclaimer:</strong> Answers are generated by AI based strictly on the text of the contract. 
          This assistant does not provide legal advice. If information is not present in the contract, it will say so instead of inventing details.
        </div>

        <div className="chat-messages-box">
          {messages.length === 0 ? (
            <div className="chat-empty-state">
              <span className="chat-icon">💬</span>
              <p>Ask anything. For example:</p>
              <div className="suggested-questions">
                <button onClick={() => setInput("What is the termination notice period?")}>
                  "What is the termination notice period?"
                </button>
                <button onClick={() => setInput("Are there any late payment fees or financial penalties?")}>
                  "Are there any late fees or penalties?"
                </button>
                <button onClick={() => setInput("What are my main responsibilities under this agreement?")}>
                  "What are my main responsibilities?"
                </button>
              </div>
            </div>
          ) : (
            messages.map((msg, index) => (
              <div key={index} className={`chat-message-bubble ${msg.role}`}>
                <div className="message-header">
                  <strong>{msg.role === "user" ? "You" : "SimpleTerms Assistant"}</strong>
                </div>
                <div className="message-content">
                  {msg.content.split("\n").map((para, i) => (
                    <p key={i}>{para}</p>
                  ))}
                </div>
              </div>
            ))
          )}

          {isLoading ? (
            <div className="chat-message-bubble model typing">
              <div className="message-header">
                <strong>SimpleTerms Assistant</strong>
              </div>
              <div className="message-content">
                <p>Thinking and scanning contract...</p>
              </div>
            </div>
          ) : null}

          {error ? (
            <div className="chat-error-banner">
              <strong>Error:</strong> {error}
            </div>
          ) : null}

          <div ref={chatEndRef} />
        </div>

        <form onSubmit={handleSubmit} className="chat-input-bar">
          <input
            type="text"
            placeholder="Ask a question about the contract terms..."
            value={input}
            onChange={(e) => setInput(e.target.value)}
            disabled={isLoading}
            aria-label="Ask a question about the contract"
          />
          <button type="submit" disabled={isLoading || !input.trim()}>
            Send
          </button>
        </form>
      </div>
    </section>
  );
}
